### ISSUE TITLE
OP_PUSHDATA3

### ISSUE THREAD

**Issue by mathiasrw** [BitcoinPHP/BitcoinScript.php#12]
Hi

Just to let you know that you should remove any references to OP_PUSHDATA3 as its not part of bitcoin script. Only OP_PUSHDATA1, OP_PUSHDATA2 and OP_PUSHDATA4 are valid. 

https://github.com/bitcoin/bitcoin/blob/master/src/script/script.h#L59-L61

**Comment by rgex** [comment]
Thank you for reporting it, I removed it.
